#!/usr/bin/env Rscript
# Prepare to publish the APIs


## Increment the version
args <- commandArgs(trailingOnly = TRUE)

current_api_version <- semver::parse_version(readLines("version.txt")[2])

new_api_version <- switch(args[1],
       "major" = semver::increment_version(current_api_version, "major", 1L),
       "minor" = semver::increment_version(current_api_version, "minor", 1L),
       semver::increment_version(current_api_version, "patch", 1L)
       )

rendered_version_info <- unlist(semver::render_version(new_api_version))

version_info <- paste0(
  "# Do not edit this file - file controlled by release.R script\n",
  rendered_version_info['major'],
  ".",
  rendered_version_info['minor'],
  ".",
  rendered_version_info['patch']
)

writeLines(version_info, "version.txt")



## Create the manifest file
rsconnect::writeManifest(
  appDir = ".",
  appFiles = c("plumber.R", "README.md", "version.txt"),
)
